apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cattle.io/creator: norman
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-dev-busybox
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-dev-busybox
    spec:
      containers:
      - image: harbor.dev.cn/test-service/busybox:1.30.1
        imagePullPolicy: Always
        name: busybox
        tty: true
